
nb_threads: 8
max_image_dimension: 512
nb_images_to_train_index: 25000


do_resize_image: True
do_preserve_aspect_ratio_for_quantized_coord: True

sift_contrastThreshold: 0.1
sift_sigma: 1.6

index_type: "IVF1024,Flat"